export const BANKS = [
  "Chase", "Wells Fargo", "Bank of America", "Citibank", "Capital One", "U.S. Bank", "PNC Bank", "TD Bank", "Truist", "Goldman Sachs",
  "Charles Schwab", "American Express", "Ally Bank", "Citizens Bank", "Fifth Third Bank", "KeyBank", "Huntington National Bank",
  "M&T Bank", "Regions Bank", "BMO Harris Bank", "First Republic Bank", "Silicon Valley Bank", "Signature Bank", "Popular Bank",
  "Union Bank", "Discover Bank", "Navy Federal Credit Union", "State Farm Bank", "Nordstrom Card Services", "Comenity Bank",
  "Synchrony Bank", "Barclays Bank Delaware", "Santander Bank", "City National Bank", "CIBC Bank USA", "First Citizens Bank",
  "East West Bank", "Associated Bank", "Frost Bank", "Pinnacle Bank", "Synovus Bank", "IberiaBank", "Hancock Whitney Bank",
  "CADENCE BANK", "COMMERCE BANK", "UMB Bank", "Great Western Bank", "Prosperity Bank", "Midland States Bank", "Simmons Bank",
  "WesBanco Bank", "United Bank", "TowneBank", "Old National Bank", "Park National Bank", "Renasant Bank", "First Hawaiian Bank",
  "Bank of Hawaii", "First Midwest Bank", "Pacific Western Bank", "Western Alliance Bank", "Banner Bank", "Washington Federal Bank",
  "Umpqua Bank", "Columbia Bank", "Glacier Bank", "First Interstate Bank", "NBT Bank", "Independent Bank", "S&T Bank", "Northwest Bank",
  "Atlantic Union Bank", "Valley National Bank", "Investors Bank", "OceanFirst Bank", "Sandy Spring Bank", "Fulton Bank", "First Commonwealth Bank",
  "Peoples Bank", "Community Bank", "Trustmark National Bank", "HomeTrust Bank", "SouthState Bank", "Ameris Bank", "Fidelity Bank",
  "Seacoast National Bank", "CenterState Bank", "Home BancShares", "First Financial Bank", "Old Second National Bank", "MainStreet Bank",
  "Cardinal Bank", "Access National Bank", "EAGLE BANK", "Burke & Herbert Bank", "United Bankshares", "FVCbank", "Virginia National Bank",
  "Blue Ridge Bank", "Freedom Bank", "Chesapeake Bank", "Middleburg Bank", "National Capital Bank", "Bank of Georgetown", "Industrial Bank",
  "City First Bank of DC", "D.C. United FCU", "Georgetown University Alumni FCU", "Treasury Federal Credit Union", "Congressional Federal Credit Union", "Wolf Trap Foundation FCU",
  "Alliant Credit Union", "Pentagon Federal Credit Union", "SchoolsFirst Federal Credit Union", "Golden 1 Credit Union", "First Tech Federal Credit Union",
  "Bethpage Federal Credit Union", "Boeing Employees Credit Union (BECU)", "Digital Federal Credit Union", "Star One Credit Union",
  "Security Service Federal Credit Union", "America First Credit Union", "Mountain America Credit Union", "San Diego County Credit Union",
  "GTE Financial", "VyStar Credit Union", "Suncoast Credit Union", "Redstone Federal Credit Union", "ESL Federal Credit Union",
  "Delta Community Credit Union", "Patelco Credit Union", "Logix Federal Credit Union", "TDECU", "Randolph-Brooks Federal Credit Union",
  "Lake Michigan Credit Union", "GreenState Credit Union", "MSU Federal Credit Union", "Landmark Credit Union", "Wright-Patt Credit Union",
  "Teachers Credit Union", "Community First Credit Union", "Canvas Credit Union", "Ent Credit Union", "Elevations Credit Union",
  "Westerra Credit Union", "Public Service Credit Union", "Credit Union of Colorado", "Bellco Credit Union", "FirstBank", "Zions Bank",
  "Woodforest National Bank", "Arvest Bank", "Iberia Bank", "Washington Trust Bank", "First Security Bank", "First National Bank of Nebraska",
  "Washington Federal", "EverBank", "Sallie Mae Bank", "BMW Bank of North America", "Toyota Financial Services", "Mercedes-Benz Financial Services",
  "Ford Motor Credit Company", "GM Financial", "Hyundai Capital America", "Nissan Motor Acceptance Corp", "American Honda Finance Corp",
  "Kia Motors Finance", "Mazda Financial Services", "Subaru Motors Finance", "Volkswagen Credit", "Audi Financial Services", "Porsche Financial Services",
  "Tesla Finance", "SoFi Bank", "Varo Bank", "Chime", "Current", "Dave", "Albert", "Empower", "MoneyLion", "Stash", "Acorns",
  "First Independent Bank", "Farmers & Merchants Bank", "California Bank & Trust", "Mechanics Bank", "Pacific Premier Bank",
  "Luther Burbank Savings", "Provident Savings Bank", "Westamerica Bank", "American Business Bank", "CTBC Bank", "Hanmi Bank",
  "Pacific City Bank", "Open Bank", "CBB Bank", "First General Bank", "Preferred Bank", "F&M Bank", "Tri Counties Bank", "Exchange Bank",
  "North Valley Bank", "Rabobank", "Guaranty Bank", "LegacyTexas Bank", "Veritex Community Bank", "Spirit of Texas Bank", "Independent Financial",
  "First Financial Bankshares", "Origin Bank", "BancorpSouth", "Renasant Bank", "Trustmark", "Hancock Whitney", "IberiaBank",
  "Home BancShares", "Simmons Bank", "Arvest Bank", "Bank OZK", "First Security Bank", "Bear State Bank", "Legacy National Bank",
  "First National Bank of Fort Smith", "Centennial Bank", "Simmons First National Bank", "PineBluff National Bank", "Simmons First Bank",
  "First National Bank of Eastern Arkansas", "Bank of Jonesboro", "First Community Bank", "Citizens Bank", "First Arkansas Bank & Trust",
  "Bank of Little Rock", "Eagle Bank & Trust", "First Financial Bank", "Relyance Bank", "Diamond Bank", "Farmers Bank & Trust",
  "Southern Bancorp", "Cadence Bank", "Synovus", "Pinnacle Financial Partners", "First Horizon Bank", "Regions", "SouthState Bank",
  "Ameris Bank", "United Community Bank", "HomeTrust Bank", "State Employees Credit Union", "Coastal Federal Credit Union",
  "Truliant Federal Credit Union", "Local Government Federal Credit Union", "Allegacy Federal Credit Union", "Self-Help Credit Union",
  "Latino Community Credit Union", "Sharonview Federal Credit Union", "Carolina Trust Federal Credit Union", "South Carolina Federal Credit Union",
  "Founders Federal Credit Union", "Palmetto Citizens Federal Credit Union", "AllSouth Federal Credit Union", "SAFE Federal Credit Union",
  "South Carolina State Credit Union", "First Citizens Bank", "Southernfirst Bank", "GrandSouth Bank", "Countybank", "Bank of Travelers Rest",
  "Blue Ridge Bank", "Pinnacle Bank", "CresCom Bank", "Coastal States Bank", "Atlantic Community Bank", "Savannah Bank", "Ameris Bank",
  "Synovus Bank", "SouthState Bank", "United Community Bank", "Fidelity Bank", "Metro City Bank", "LGE Community Credit Union",
  "Georgia United Credit Union", "Associated Credit Union", "Delta Community Credit Union", "Robins Financial Credit Union",
  "Peach State Federal Credit Union", "Atlanta Postal Credit Union", "BrandBank", "Piedmont Bank", "Signature Bank of Georgia",
  "Heritage Southeast Bank", "Ameris Bank", "Colony Bank", "Synovus Bank", "Sea Island Bank", "Coastal States Bank", "Sea Island Bank",
  "Bank of the Ozarks", "Stonegate Bank", "CenterState Bank", "IberiaBank", "Hancock Whitney", "Seacoast Bank", "Valley Bank",
  "Ameris Bank", "Synovus Bank", "Raymond James Bank", "BankUnited", "City National Bank of Florida", "Ocean Bank", "Amerant Bank",
  "Apollo Bank", "Banesco USA", "Pacifica Federal Credit Union", "Space Coast Credit Union", "Suncoast Credit Union", "GTE Financial",
  "MidFlorida Credit Union", "Fairwinds Credit Union", "Addition Financial Credit Union", "First Florida Credit Union",
  "First Commerce Credit Union", "Community First Credit Union of Florida", "Florida Central Credit Union", "Florida United Methodist Credit Union",
  "Achieva Credit Union", "Power Financial Credit Union", "Tropical Financial Credit Union", "We Florida Financial", "BrightStar Credit Union",
  "South Florida Federal Credit Union", "Miami Federal Credit Union", "Dade County Federal Credit Union", "JetStream Federal Credit Union",
  "San Antonio Citizens Federal Credit Union", "Gulf Winds Credit Union", "PenAir Credit Union", "Eglin Federal Credit Union",
  "Okaloosa County Teachers FCU", "First City Credit Union", "Tyndall Federal Credit Union", "Community South Credit Union",
  "Emerald Coast Federal Credit Union", "Envision Credit Union", "First Commerce Credit Union", "Florida State University Credit Union",
  "Tallahassee-Leon Federal Credit Union", "Campco Federal Credit Union", "Reliant Federal Credit Union", "Wyoming Community Bank",
  "First Northern Bank of Wyoming", "Bank of Jackson Hole", "Wyoming Bank & Trust", "First State Bank of Wheatland",
  "First National Bank of Gillette", "Pinnacle Bank", "Western States Bank", "ANB Bank", "Glacier Bank", "First Interstate Bank",
  "Wells Fargo", "Chase", "Bank of America", "US Bank", "KeyBank", "Washington Federal",
];
